import { PageHeader } from "@/components/ui";
import { getCurrentRole } from "@/lib/current-role";
import { can } from "@/lib/roles";
import { getReportSnapshots } from "@/lib/reports";
import { formatUsd, formatCount } from "@/lib/money";
import { generateReportNow } from "@/app/actions/reports";
import type { WeeklyReportPayload } from "@/lib/reports";

export const dynamic = "force-dynamic";

// ---------------------------------------------------------------------------
// Generate-now button — a plain HTML form drives the server action so this
// page stays fully server-rendered (no client component needed).
// ---------------------------------------------------------------------------

function GenerateButton() {
  return (
    <form action={generateReportNow}>
      <button
        type="submit"
        className="rounded-md bg-brand px-4 py-2 text-sm font-medium text-brand-ink hover:opacity-90 transition-opacity"
      >
        Generate now
      </button>
    </form>
  );
}

// ---------------------------------------------------------------------------
// Report card
// ---------------------------------------------------------------------------

function ReportCard({
  title,
  periodStart,
  periodEnd,
  payload,
  generatedBy,
  createdAt,
}: {
  title: string;
  periodStart: Date;
  periodEnd: Date;
  payload: unknown;
  generatedBy: string;
  createdAt: Date;
}) {
  const p = payload as WeeklyReportPayload;
  const totals = p?.totals;

  const fmt = (d: Date) =>
    d.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" });

  return (
    <div className="rounded-xl border border-border bg-surface p-5 space-y-3">
      <div className="flex items-start justify-between gap-4">
        <div>
          <h3 className="text-sm font-semibold text-foreground">{title}</h3>
          <p className="mt-0.5 text-xs text-muted">
            {fmt(periodStart)} – {fmt(periodEnd)}
          </p>
        </div>
        <span className="shrink-0 rounded-full bg-black/[0.04] px-2.5 py-0.5 text-xs font-medium text-muted">
          {fmt(createdAt)}
        </span>
      </div>

      {totals && (
        <div className="grid grid-cols-3 gap-3">
          <Stat label="Meals served" value={formatCount(totals.mealsServed)} />
          <Stat
            label="Dollars delivered"
            value={formatUsd(totals.dollarsDeliveredCents, { maximumFractionDigits: 0 })}
          />
          <Stat
            label="Contribution margin"
            value={formatUsd(totals.contributionMarginCents, { maximumFractionDigits: 0 })}
          />
        </div>
      )}

      <p className="text-xs text-muted">Generated by {generatedBy}</p>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-lg border border-border bg-black/[0.02] px-3 py-2">
      <p className="text-[10px] uppercase tracking-wide text-muted">{label}</p>
      <p className="mt-0.5 text-base font-semibold tabular-nums text-foreground">{value}</p>
    </div>
  );
}

// ---------------------------------------------------------------------------
// Page
// ---------------------------------------------------------------------------

export default async function ReportsPage() {
  const [role, snapshots] = await Promise.all([
    getCurrentRole(),
    getReportSnapshots(),
  ]);

  const canGenerate = can(role, "view:financials");

  return (
    <div className="px-4 py-6 sm:px-6 lg:px-8 max-w-[900px]">
      <PageHeader
        title="Reports"
        subtitle="Automated weekly funder &amp; board summaries"
      >
        {canGenerate && <GenerateButton />}
      </PageHeader>

      <div className="mt-6 space-y-4">
        {snapshots.length === 0 ? (
          <div className="rounded-xl border border-dashed border-border px-6 py-10 text-center text-sm text-muted">
            No reports yet — the weekly cron runs Mondays, or generate one now.
          </div>
        ) : (
          snapshots.map((s) => (
            <ReportCard
              key={s.id}
              title={s.title}
              periodStart={s.periodStart}
              periodEnd={s.periodEnd}
              payload={s.payload}
              generatedBy={s.generatedBy}
              createdAt={s.createdAt}
            />
          ))
        )}
      </div>
    </div>
  );
}
